# This file is part of the Ideal Library
# Copyright (C) 2011 Rafael Fernández López <ereslibre@ereslibre.es>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 3 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this library; see the file COPYING.LIB.  If not, write to
# the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.

import Options

def configure(conf):
	if not Options.options.release:
		conf.sub_config('tests')

	if conf.env['DEST_OS'] in ['linux', 'darwin']:
		conf.env['LIB_CORE'] = ['pthread']

def build(bld):
	obj = bld(features = 'cxx cxxshlib',
	          source   = bld.path.ant_glob('*.cpp'),
	          target   = 'idealcore',
	          includes = '..',
	          use      = ['CORE'],
	          vnum     = bld.env['LIBVERSION'])

	if bld.env['DEST_OS'] in bld.env['POSIX_PLATFORMS']:
		obj.source += bld.path.ant_glob('private/posix/*.cpp')

	bld(features = 'subst',
	    source   = 'idealcore.pc.in',
	    target   = 'idealcore.pc',
	    PREFIX   = bld.env['PREFIX'],
	    LIBS     = '-lidealcore',
	    VERSION  = bld.env['LIBVERSION'])

	bld.install_files('${PREFIX}/lib/pkgconfig', 'idealcore.pc')
	bld.install_files('${PREFIX}/include/ideal/core', bld.path.ant_glob('*.h'))
	bld.install_files('${PREFIX}/include/ideal/core/interfaces', bld.path.ant_glob('interfaces/*.h'))

	if not bld.env['RELEASE']:
		bld.add_subdirs('tests')
